SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `sys_carcinoma`;
CREATE TABLE `sys_carcinoma` (
  `carcinoma_id` int(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `alcoholism` varchar(30) DEFAULT'',
  `vh_amn` varchar(30) DEFAULT'',
  `hepatotoxic` varchar(30) DEFAULT'',
  `THepatitis` varchar(30) DEFAULT'',
  `hospital` varchar(30) DEFAULT'',
  `surgery` varchar(30) DEFAULT'',
  `gallstones` varchar(30) DEFAULT'',
  `choledocholithotomy` varchar(30) DEFAULT'',
  `injections` varchar(30) DEFAULT'',
  `transfusion` varchar(30) DEFAULT'',
  `ChHepatitis` varchar(30) DEFAULT'',
  `sex` varchar(30) DEFAULT'',
  `age` varchar(30) DEFAULT '' COMMENT '年龄',
  `PBC` varchar(30) DEFAULT'',
  `fibrosis` varchar(30) DEFAULT'',
  `diabetes` varchar(30) DEFAULT'',
  `obesity` varchar(30) DEFAULT'',
  `Steatosis` varchar(30) DEFAULT'',
  `Cirrhosis` varchar(30) DEFAULT'',
  `Hyperbilirubinemia` varchar(30) DEFAULT'',
  `triglycerides` varchar(30) DEFAULT'',
  `RHepatitis` varchar(30) DEFAULT'',
  `fatigue` varchar(30) DEFAULT'',
  `bilirubin` varchar(30) DEFAULT'',
  `itching` varchar(30) DEFAULT'',
  `upper_pain` varchar(30) DEFAULT'',
  `fat` varchar(30) DEFAULT'',
  `pain_ruq` varchar(30) DEFAULT'',
  `pressure_ruq` varchar(30) DEFAULT'',
  `phosphatase` varchar(30) DEFAULT'',
  `skin` varchar(30) DEFAULT'',
  `ama` varchar(30) DEFAULT'',
  `le_cells` varchar(30) DEFAULT'',
  `joints` varchar(30) DEFAULT'',
  `pain` varchar(30) DEFAULT'',
  `proteins` varchar(30) DEFAULT'',
  `edema` varchar(30) DEFAULT'',
  `platelet` varchar(30) DEFAULT'',
  `inr` varchar(30) DEFAULT'',
  `bleeding` varchar(30) DEFAULT'',
  `flatulence` varchar(30) DEFAULT'',
  `alcohol` varchar(30) DEFAULT'',
  `encephalopathy` varchar(30) DEFAULT'',
  `urea` varchar(30) DEFAULT'',
  `ascites` varchar(30) DEFAULT'',
  `hepatomegaly` varchar(30) DEFAULT'',
  `hepatalgia` varchar(30) DEFAULT'',
  `density` varchar(30) DEFAULT'',
  `ESR` varchar(30) DEFAULT'',
  `alt` varchar(30) DEFAULT'',
  `ast` varchar(30) DEFAULT'',
  `amylase` varchar(30) DEFAULT'',
  `ggtp` varchar(30) DEFAULT'',
  `cholesterol` varchar(30) DEFAULT'',
  `hbsag` varchar(30) DEFAULT'',
  `hbsag_anti` varchar(30) DEFAULT'',
  `anorexia` varchar(30) DEFAULT'',
  `nausea` varchar(30) DEFAULT'',
  `spleen` varchar(30) DEFAULT'',
  `consciousness` varchar(30) DEFAULT'',
  `spiders` varchar(30) DEFAULT'',
  `jaundice` varchar(30) DEFAULT'',
  `albumin` varchar(30) DEFAULT'',
  `edge` varchar(30) DEFAULT'',
  `irregular_liver` varchar(30) DEFAULT'',
  `hbc_anti` varchar(30) DEFAULT'',
  `hcv_anti` varchar(30) DEFAULT'',
  `palms` varchar(30) DEFAULT'',
  `hbeag` varchar(30) DEFAULT'',
  

  PRIMARY KEY (`carcinoma_id`)
) ENGINE=InnoDB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='carcinoma检测表';


